"""initial schema

Revision ID: fcd5d99459ee
Revises: 
Create Date: 2026-05-30 08:33:25.183393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd5d99459ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('commissioner_token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('commissioner_token')
    )
    op.create_table('real_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('draft_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('current_pick', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('pick_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('real_team_id', sa.Integer(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('account_name_override', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['real_team_id'], ['real_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('deaths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('cumulative_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hiscore_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('snapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_xp', sa.BigInteger(), nullable=False),
    sa.Column('attack_xp', sa.BigInteger(), nullable=False),
    sa.Column('defence_xp', sa.BigInteger(), nullable=False),
    sa.Column('strength_xp', sa.BigInteger(), nullable=False),
    sa.Column('hitpoints_xp', sa.BigInteger(), nullable=False),
    sa.Column('ranged_xp', sa.BigInteger(), nullable=False),
    sa.Column('prayer_xp', sa.BigInteger(), nullable=False),
    sa.Column('magic_xp', sa.BigInteger(), nullable=False),
    sa.Column('cooking_xp', sa.BigInteger(), nullable=False),
    sa.Column('woodcutting_xp', sa.BigInteger(), nullable=False),
    sa.Column('fletching_xp', sa.BigInteger(), nullable=False),
    sa.Column('fishing_xp', sa.BigInteger(), nullable=False),
    sa.Column('firemaking_xp', sa.BigInteger(), nullable=False),
    sa.Column('crafting_xp', sa.BigInteger(), nullable=False),
    sa.Column('smithing_xp', sa.BigInteger(), nullable=False),
    sa.Column('mining_xp', sa.BigInteger(), nullable=False),
    sa.Column('herblore_xp', sa.BigInteger(), nullable=False),
    sa.Column('agility_xp', sa.BigInteger(), nullable=False),
    sa.Column('thieving_xp', sa.BigInteger(), nullable=False),
    sa.Column('slayer_xp', sa.BigInteger(), nullable=False),
    sa.Column('farming_xp', sa.BigInteger(), nullable=False),
    sa.Column('runecraft_xp', sa.BigInteger(), nullable=False),
    sa.Column('hunter_xp', sa.BigInteger(), nullable=False),
    sa.Column('construction_xp', sa.BigInteger(), nullable=False),
    sa.Column('pvp_kills', sa.Integer(), nullable=False),
    sa.Column('deaths_cumulative', sa.Integer(), nullable=False),
    sa.Column('barrows_chests', sa.Integer(), nullable=False),
    sa.Column('wintertodt', sa.Integer(), nullable=False),
    sa.Column('tempoross', sa.Integer(), nullable=False),
    sa.Column('guardians_of_the_rift', sa.Integer(), nullable=False),
    sa.Column('giant_mole', sa.Integer(), nullable=False),
    sa.Column('king_black_dragon', sa.Integer(), nullable=False),
    sa.Column('chaos_fanatic', sa.Integer(), nullable=False),
    sa.Column('chaos_elemental', sa.Integer(), nullable=False),
    sa.Column('scorpia', sa.Integer(), nullable=False),
    sa.Column('crazy_archaeologist', sa.Integer(), nullable=False),
    sa.Column('deranged_archaeologist', sa.Integer(), nullable=False),
    sa.Column('kalphite_queen', sa.Integer(), nullable=False),
    sa.Column('kraken', sa.Integer(), nullable=False),
    sa.Column('thermonuclear_smoke_devil', sa.Integer(), nullable=False),
    sa.Column('sarachnis', sa.Integer(), nullable=False),
    sa.Column('skotizo', sa.Integer(), nullable=False),
    sa.Column('dagannoth_prime', sa.Integer(), nullable=False),
    sa.Column('dagannoth_rex', sa.Integer(), nullable=False),
    sa.Column('dagannoth_supreme', sa.Integer(), nullable=False),
    sa.Column('zalcano', sa.Integer(), nullable=False),
    sa.Column('abyssal_sire', sa.Integer(), nullable=False),
    sa.Column('cerberus', sa.Integer(), nullable=False),
    sa.Column('corporeal_beast', sa.Integer(), nullable=False),
    sa.Column('general_graardor', sa.Integer(), nullable=False),
    sa.Column('commander_zilyana', sa.Integer(), nullable=False),
    sa.Column('kreearra', sa.Integer(), nullable=False),
    sa.Column('kril_tsutsaroth', sa.Integer(), nullable=False),
    sa.Column('grotesque_guardians', sa.Integer(), nullable=False),
    sa.Column('zulrah', sa.Integer(), nullable=False),
    sa.Column('vorkath', sa.Integer(), nullable=False),
    sa.Column('alchemical_hydra', sa.Integer(), nullable=False),
    sa.Column('phantom_muspah', sa.Integer(), nullable=False),
    sa.Column('nex', sa.Integer(), nullable=False),
    sa.Column('chambers_of_xeric', sa.Integer(), nullable=False),
    sa.Column('theatre_of_blood', sa.Integer(), nullable=False),
    sa.Column('tombs_of_amascut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('drafted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'player_id'),
    sa.UniqueConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_entries')
    op.drop_table('hiscore_snapshots')
    op.drop_table('deaths')
    op.drop_table('players')
    op.drop_table('managers')
    op.drop_table('draft_states')
    op.drop_table('real_teams')
    op.drop_table('leagues')
    # ### end Alembic commands ###
